#!/bin/bash
# ==================================================
#  KoolDots (2026)
#  Project URL: https://github.com/LinuxBeginnings
#  License: GNU GPLv3
#  SPDX-License-Identifier: GPL-3.0-or-later
# ==================================================
# 💫 https://github.com/LinuxBeginnings 💫 #
# hyprsysteminfo #

#specific branch or release (fallback)
tag_default="auto"
if [ -z "${HYPRSYSTEMINFO_TAG:-}" ]; then
  TAGS_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/hypr-tags.env"
  [ -f "$TAGS_FILE" ] && source "$TAGS_FILE"
fi
TAG_SRC="${HYPRSYSTEMINFO_TAG:-$tag_default}"
[[ "$TAG_SRC" =~ ^(auto|latest)$ ]] && git_ref="" || git_ref="$TAG_SRC"

DO_INSTALL=1
[ "$1" = "--dry-run" ] || [ "${DRY_RUN}" = "1" ] || [ "${DRY_RUN}" = "true" ] && { DO_INSTALL=0; echo "${NOTE} DRY RUN: install step will be skipped."; }

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PARENT_DIR="$SCRIPT_DIR/.."
cd "$PARENT_DIR" || exit 1
source "$(dirname "$(readlink -f "$0")")/Global_functions.sh"

LOG="Install-Logs/install-$(date +%d-%H%M%S)_hyprsysteminfo.log"
MLOG="install-$(date +%d-%H%M%S)_hyprsysteminfo2.log"

SRC_DIR="$SRC_ROOT/hyprsysteminfo"
rm -rf "$SRC_DIR" 2>/dev/null || true
printf "${INFO} Installing ${YELLOW}hyprsysteminfo ${git_ref:-default-branch}${RESET} ...\n"
if git clone --recursive ${git_ref:+-b "$git_ref"} https://github.com/hyprwm/hyprsysteminfo.git "$SRC_DIR"; then
    cd "$SRC_DIR" || exit 1
    BUILD_DIR="$BUILD_ROOT/hyprsysteminfo"
    mkdir -p "$BUILD_DIR"
    # Replace #embed with an autogenerated bytes include for toolchains lacking it
    ICONS_HDR="$SRC_DIR/src/icons/Icons.hpp"
    ICON_SRC="$SRC_DIR/resource/hyprlandlogo.svg"
    ICON_INC="$SRC_DIR/src/icons/hyprlandlogo.bytes.inc"
    if [ -f "$ICONS_HDR" ] && [ -f "$ICON_SRC" ] && grep -q '^[[:space:]]*#embed' "$ICONS_HDR"; then
        if ! command -v xxd >/dev/null 2>&1; then
            echo "${NOTE} xxd not found; attempting to install xxd..." | tee -a "$LOG"
            install_package "xxd" 2>&1 | tee -a "$LOG" || true
        fi
        if command -v xxd >/dev/null 2>&1; then
            xxd -i -g 1 -c 16 "$ICON_SRC" | awk 'BEGIN{f=0} /^\{/ {f=1; next} /^\};/ {f=0} f' >"$ICON_INC" || true
            sed -ri 's|^[[:space:]]*#embed[[:space:]]+\"\\.{0,2}/\\.{0,2}/resource/hyprlandlogo\\.svg\"[[:space:]]*$|#include \"hyprlandlogo.bytes.inc\"|g' "$ICONS_HDR" || true
        else
            echo "${NOTE} xxd still unavailable; skipping #embed replacement." | tee -a "$LOG"
        fi
    fi
    if [ -f CMakeLists.txt ]; then
        cmake -S . -B "$BUILD_DIR" -DCMAKE_BUILD_TYPE=Release 2>&1 | tee -a "$MLOG"
        cmake --build "$BUILD_DIR" -j "$(nproc 2>/dev/null || getconf _NPROCESSORS_CONF)" 2>&1 | tee -a "$MLOG"
        if [ $DO_INSTALL -eq 1 ]; then sudo cmake --install "$BUILD_DIR" 2>&1 | tee -a "$MLOG"; else echo "${NOTE} DRY RUN: skip install" | tee -a "$MLOG"; fi
    elif [ -f meson.build ]; then
        meson setup "$BUILD_DIR" --buildtype=release 2>&1 | tee -a "$MLOG"
        meson compile -C "$BUILD_DIR" 2>&1 | tee -a "$MLOG"
        if [ $DO_INSTALL -eq 1 ]; then sudo meson install -C "$BUILD_DIR" 2>&1 | tee -a "$MLOG"; else echo "${NOTE} DRY RUN: skip install" | tee -a "$MLOG"; fi
    else
        echo "${ERROR} Unknown build system for hyprsysteminfo" | tee -a "$MLOG"
    fi
    mv "$MLOG" "$PARENT_DIR/Install-Logs/" || true
else
    echo -e "${ERROR} Download failed for ${YELLOW}hyprsysteminfo${RESET}" 2>&1 | tee -a "$LOG"
fi
printf "\n%.0s" {1..1}
